SRCS_WAVEFILE := \
	$(SRCS_WAVEFILE_DIR)/CWaveFile.cpp \
	$(SRCS_WAVEFILE_DIR)/ChunkOperator/BChunkOperator.cpp \
	$(SRCS_WAVEFILE_DIR)/ChunkOperator/CChunkFactory.cpp \
	$(SRCS_WAVEFILE_DIR)/ChunkOperator/CDataChunkOperator.cpp \
	$(SRCS_WAVEFILE_DIR)/ChunkOperator/CFmtChunkOperator.cpp \
	$(SRCS_WAVEFILE_DIR)/ChunkOperator/COtherChunkOperator.cpp \
	$(SRCS_WAVEFILE_DIR)/ChunkOperator/CRIFFChunkOperator.cpp \
	$(SRCS_WAVEFILE_DIR)/SampleOperator/CSampleOperator16.cpp \
	$(SRCS_WAVEFILE_DIR)/SampleOperator/CSampleOperator8.cpp \
	$(SRCS_WAVEFILE_DIR)/SampleOperator/CSampleOperatorOther.cpp \
	$(SRCS_WAVEFILE_DIR)/Utility/CWaveFileUtility.cpp \
