SRCS_WAVEFORMAT_OPERATOR := \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveForm/BWaveForm.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/CWaveFile.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/ChunkOperator/BChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/ChunkOperator/CChunkFactory.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/ChunkOperator/CDataChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/ChunkOperator/CFmtChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/ChunkOperator/COtherChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/ChunkOperator/CRIFFChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/SampleOperator/CSampleOperator16.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/SampleOperator/CSampleOperator8.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/SampleOperator/CSampleOperatorOther.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFile/Utility/CWaveFileUtility.cpp \
