SRCS_WAVEFORMAT_OPERATOR := \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/BWaveForm/BWaveForm.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/CWaveFile.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/BChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/CChunkFactory.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/CDataChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/CFmtChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/COtherChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/CRIFFChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/ChunkOperator/CWAVEChunkOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/SampleOperator/CSampleOperator16.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/SampleOperator/CSampleOperator8.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/SampleOperator/CSampleOperatorOther.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/CWaveFile/Utility/CWaveFileUtility.cpp \
