SRCS_WAVEFORMAT_OPERATOR := \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/BSoundInformation.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/CWaveFormatOperatorUtility.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/CWaveFormatOperator.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/WriteSample/CFactoryWriteSample.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/WriteSample/CWriteSample8.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/WriteSample/CWriteSample16.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/WriteSample/CWriteSampleOther.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/ReadSample/CReadSample8.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/ReadSample/CReadSample16.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/ReadSample/CReadSampleOther.cpp \
	$(SRCS_WAVEFORMAT_OPERATOR_DIR)/WaveFormatOperator/ReadSample/CFactoryReadSample.cpp \



